### ISSUE TITLE
Project [Work]

### ISSUE THREAD

**Issue by TilinMamarre69** [LizEuan08/Portfolio-3er-parcial.github.io#10]
Requiero una sección en la cual los clientes interesados puedan contactarnos con un botón

- [x] Botón

**Comment by TilinMamarre69** [comment]
Se realizó la página y el Pull fue aprobado.

**Comment by TilinMamarre69** [comment]
Se linkeará el botón cuando se realice la página de Contact.

**Comment by LizEuan08** [comment]
https://github.com/LizEuan08/Portfolio-3er-parcial.github.io/pull/21

**Comment by LizEuan08** [comment]
https://github.com/LizEuan08/Portfolio-3er-parcial.github.io/pull/21
