### ISSUE TITLE
Our Priority

### ISSUE THREAD

**Issue by TilinMamarre69** [LizEuan08/Portfolio-3er-parcial.github.io#11]
#https://github.com/LizEuan08/Portfolio-3er-parcial.github.io/pull/17
Requiero una sección que incluya las prioridades de la empresa sobre el usuario

- [ ] Texto de prioridades
- [ ] Botón de "Our Work"

**Comment by LizEuan08** [comment]
https://github.com/LizEuan08/Portfolio-3er-parcial.github.io/pull/17
