### ISSUE TITLE
Our Recent Work 

### ISSUE THREAD

**Issue by TilinMamarre69** [LizEuan08/Portfolio-3er-parcial.github.io#9]
Requiero una sección que contenga los últimos trabajos realizados

- [x] Testcovid
- [x] Edubin
- [x] Robert Berski
- [x] Fastcart

**Comment by TilinMamarre69** [comment]
Es probable que hayan pequeños márgenes de error, se repararán en el siguiente Pull Request, buenas tardes.

**Comment by LizEuan08** [comment]
https://github.com/LizEuan08/Portfolio-3er-parcial.github.io/pull/21
